apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: comp4000
  name: server
spec:
  replicas: 10
  selector:
    matchLabels:
      app: comp4000
      component: server
  template:
    metadata:
      labels:
        app: comp4000
        component: server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:
                    app: comp4000
                    component: server
      containers:
      - name: printerfacts
        image: (IMAGE_NAME)
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CASSANDRA_IP
            value: 10.96.0.200

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: comp4000
    component: server
  name: printerfacts
spec:
  type: LoadBalancer
  clusterIP: 10.96.0.201
  selector:
    app: comp4000
    component: server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
